<img src="images/numpy/numpy.png" style="width:50%;height:50%;">

### 1. Giới thiệu
Numpy là một thư viện của Python hỗ trợ việc tính toán trên mảng nhiều chiều. Một mảng Numpy là một tập hợp các giá trị cùng kiểu dữ liệu và được đánh số bằng các số nguyên dương. Numpy là Module quan trọng cho việc sử lý dữ liệu và có thể chuyển đổi qua kiểu dữ liệu Tensor trong Tensorflow và Pytorch.

Mọi chi tiết về Numpy đều được công bố trên trang chủ chính thức: https://numpy.org/doc/

Các bạn có thể cài đặt Numpy theo hướng dẫn dưới đây:
- [Dành cho máy Mac và Linux](https://machinelearningcoban.com/faqs/#-huong-dan-cai-dat-python-va-cac-thu-vien-tren-macos) 
- [Dành cho Windows](https://machinelearningcoban.com/faqs/#-huong-dan-cai-dat-python-va-cac-thu-vien-tren-windows)

Sau khi cài đặt xong, chúng ta cần phải import thư viện vào để sử dụng:

In [1]:
import numpy as np

Từ khoá `as` trong Python giúp chúng ta viết gọn tên của thư viện giúp tiện lợi cho việc sử dụng về sau.

### 2. Nội dung 

Nội dung chính trong bài ngày hôm nay chúng ta sẽ cùng tìm hiểu về:
- Tạo mảng Numpy (ndarray) 
- Kiểu dữ liệu (Datatypes)
- Array Indexing 
- Phép toán trên mảng 
- Broadcasting

#### 2.1 Tạo mảng Numpy (ndarray)

Tạo ndarray từ List 



In [2]:
# Tạo ndarray từ list

import numpy as np

# tạo list 
l = list(range(1, 4))

# tạo ndarray
data = np.array(l)

print(data)
print(data[0], data[1])

[1 2 3]
1 2


<img src="images/numpy/chap5_np_1.png" style="width:20%;height:20%;">


Sử dụng thuộc tính `shape` và hàm `type()` cho mảng Numpy 

In [3]:
# Tạo ndarray từ list

import numpy as np

# tạo list 
l = list(range(1, 4))

# tạo ndarray
data = np.array(l)

print(data)
print(type(data))
print(type(data[0]))
print(data.shape)

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int64'>
(3,)


Thay đổi `shape` của mảng sử dụng `reshape`

In [4]:
# thay đổi shape của một mảng

import numpy as np

arr1 = np.arange(12)
print(arr1.shape)

arr2 = arr1.reshape((3, 4))
print(arr2.shape)

(12,)
(3, 4)


Thay đổi giá trị của một phần tử 



In [5]:
# thay đổi giá trị phần tử 

import numpy as np

l = list(range(1, 4))
data = np.array(l)
print(data)

data[0] = 8
print(data)

[1 2 3]
[8 2 3]


<img src="images/numpy/chap5_np_2.png" style="width:20%;height:20%;">


Tạo ndarray với hàm `zeros()`

In [6]:
# tạo một numpy array với tất cả các phần tử là 0

import numpy as np

# shape: 2 dòng, 3 cột 
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


<img src="images/numpy/chap5_np_3.png" style="width:20%;height:20%;">


Tạo ndarray với hàm `ones()`

In [7]:
# tạo một numpy array với tất cả phần tử là 1

import numpy as np

# numpy.ones(shape, dtype=None, order='C')
# shape: 2 dòng, 3 cột
arr = np.ones((2, 3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


<img src="images/numpy/chap5_np_4.png" style="width:20%;height:20%;">


Tạo ndarray với hàm `full()`

In [8]:
# tạo một numpy array với tất cả phần tử là hằng số K 

import numpy as np 

# numpy.full(shape, fill_value, dtype=None, order='C')
# shape: 2 dòng, 3 cột - với K = 9
arr = np.full((2, 3), 9)
print(arr)

[[9 9 9]
 [9 9 9]]


<img src="images/numpy/chap5_np_5.png" style="width:20%;height:20%;">


Tạo ma trận đường chéo 

In [9]:
# tạo một numpy array với đường chéo là số 1
# số 0 được điền vào những ô phần tử còn lại 

import numpy as np

# numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C')
# shape: 2 dòng, 3 cột
arr = np.eye(3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<img src="images/numpy/chap5_np_6.png" style="width:20%;height:20%;">

Tạo một numpy array với giá trị ngẫu nhiên 

In [10]:
# tạo một numpy array với giá trị ngẫu nhiên

import numpy as np

# numpy.random.random(size=None)
# shape: 2 dòng, 3 cột; với phần tử có giá trị ngẫu nhiên 

arr = np.random.random((2,3))
print(arr)

[[0.55136636 0.90697043 0.80751447]
 [0.50399661 0.53732573 0.94443   ]]


Điều kiện cho mảng numpy 

In [11]:
import numpy as np

arr = np.arange(10)
print(arr)

out = np.where(arr < 5, arr, 10*arr)
print(out)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4 50 60 70 80 90]


Chuyển mảng về một chiều 

In [12]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
out = arr.flatten()

print(arr)
print(out)

[[1 2]
 [3 4]]
[1 2 3 4]


#### 2.2 Kiểu dữ liệu (Datatypes)

Mảng numpy chứa các phần tử cùng kiểu dữ liệu. Numpy cung cấp một tập hợp các kiểu dữ liệu mà chúng có thể sử dụng để xây dựng các mảng.

In [13]:
import numpy as np

# int32
arr1 = np.array([1, 2])
print(arr1.dtype)

# float64
arr2 = np.array([1.0, 2.0])
print(arr2.dtype)

# int64
arr3 = np.array([1, 2], dtype = np.int64)
print(arr3.dtype)

int64
float64
int64


#### 2.3 Array Indexing 

Numpy cung cấp một số cách để truy xuất phần tử trong mảng. Truy xuất phần tử dùng kỹ thuật slicing tương tự như danh sách (list) trong Python.

**Ví dụ 1:** Lấy các phần tử từ mảng 2 chiều như sau:

In [14]:
import numpy as np

# Khởi tạo numpy array có shape = (2, 3) có giá trị như sau:
# [[ 1 2 3]
#  [ 4 6 7]]
a_arr = np.array([[1,2,3],[5,6,7]])
print('a_arr: \n', a_arr)

# Sử dụng slicing để tạo mảng b bằng cách lấy 2 hàng đầu tiên
# và cột 1, 2. Như vậy b sẽ có shape = (2, 3):
# [[2 3]
#  [6 7]]
b_arr = a_arr[:, 1:3]
print('b_arr: \n', b_arr)

a_arr: 
 [[1 2 3]
 [5 6 7]]
b_arr: 
 [[2 3]
 [6 7]]


<img src="images/numpy/chap5_np_9.png" style="width:30%;height:30%;">

Việc một mảng mới được tạo ra từ Slicing sẽ có **cùng địa chỉ** với mảng gốc. Nếu thay đổi một trong hai mảng này thì mảng còn lại cũng thay đổi theo.

In [15]:
import numpy as np

# Khởi tạo numpy array có shape = (2, 3) có giá trị như sau:
# [[ 1 2 3]
#  [ 4 6 7]]
a_arr = np.array([[1,2,3],[5,6,7]])
print('a_arr: \n', a_arr)

# Sử dụng slicing để tạo mảng b bằng cách lấy 2 hàng đầu tiên
# và cột 1, 2. Như vậy b sẽ có shape = (2, 3):
# [[2 3]
#  [6 7]]
b_arr = a_arr[:, 1:3]
print('b_arr: \n', b_arr)

print('Truoc khi thay doi: \n', a_arr[0, 1])
b_arr[0, 0] = 99
print('Sau khi thay doi: \n', a_arr[0, 1])

a_arr: 
 [[1 2 3]
 [5 6 7]]
b_arr: 
 [[2 3]
 [6 7]]
Truoc khi thay doi: 
 2
Sau khi thay doi: 
 99


<img src="images/numpy/chap5_np_10.png"  style="width:40%;height:40%;">

**Ví dụ 2:** Lấy một dòng dữ liệu

In [16]:
import numpy as np 

# Tạo một numpy array có shape (3, 4) với giá trị như sau:
# [[ 1 2 3 ] 
#  [ 5 6 7 ]
#  [ 9 10 11 ]] 
arr = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])

# Hai cách truy cập dữ liệu ở hàng giữa của mảng
# Cách 1: Dùng kết hợp chỉ số và slice -> được array mới có số chiều thấp hơn 
# Cách 2: Nếu chỉ dùng slice ta sẽ có array mới có cùng số chiều với array gốc 

# Cách 1: số chiều giảm 
row_r1 = arr[1, :]

# Cách 2: số chiều được giữ nguyên 
row_r2 = arr[1:2, :]

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

[5 6 7] (3,)
[[5 6 7]] (1, 3)


<img src="images/numpy/chap5_np_11.png" style="width:40%;height:40%;">

**Ví dụ 3:** Lấy một cột dữ liệu 

In [17]:
import numpy as np 

# Tạo một numpy array có shape (3, 4) với giá trị như sau:
# [[ 1 2 3 ] 
#  [ 5 6 7 ]
#  [ 9 10 11 ]] 
arr = np.array([[1, 2, 3], [5, 6, 7], [9, 10, 11]])

# Hai cách truy cập dữ liệu ở cột giữa của mảng
# Cách 1: Dùng kết hợp chỉ số và slice -> được array mới có số chiều thấp hơn 
# Cách 2: Nếu chỉ dùng slice ta sẽ có array mới có cùng số chiều với array gốc 

# Cách 1: số chiều giảm 
col_r1 = arr[:, 1]

# Cách 2: số chiều được giữ nguyên 
col_r2 = arr[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


<img src="images/numpy/chap5_np_13.png" style="width:30%;height:30%;">

**Boolean indexing:** Cho phép chúng ta chọn ra các phần tử tùy ý của một mảng. Kiểu truy xuất này thường được sử dụng để chọn ra các phần tử thỏa mãn điều kiện nào đó.

**Ví dụ 4:** Tìm các vị trí thoả mãn điều kiện 

In [18]:
import numpy as np

a_arr = np.array([[1, 2], [3, 4], [5, 6]])
print(a_arr)

# Tìm các phần tử lớn hơn 2
# Trả về 1 mảng Boolean có số chiều như mảng a_arr
# và giá trị tại mỗi phần từ là True nếu phần tử của a tại đó > 2,
# False cho trường hợp ngược lại 

bool_idx = (a_arr > 2)
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


<img src="images/numpy/chap5_np_15.png" style="width:30%;height:30%;">

**Ví dụ 5:** Tìm các vị trí thoả mãn điều kiện và lấy phần tử tương ứng 

In [19]:
import numpy as np

a_arr = np.array([[1, 2], [3, 4], [5, 6]])
print(a_arr)

# Tìm các phần tử lớn hơn 2
# Trả về 1 mảng Boolean có số chiều như mảng a_arr
# và giá trị tại mỗi phần từ là True nếu phần tử của a tại đó > 2,
# False cho trường hợp ngược lại 

bool_idx = (a_arr > 2)
print('bool_idx: \n', bool_idx)

# Chúng ta sẽ sử dụng boolean array indexing để xây dựng mảng 1 chiều
# Bao gồm các phần tử tương ứng với giá trị True của bool_idx 

# Ví dụ ở đây in ra các giá trị của a_arr >2, sử dụng array bool_idx đã tạo
out = a_arr[bool_idx]
print('\nMethod 1:\n', out)

# một cách ngắn gọn hơn 
print('\nMethod 2:\n', a_arr[a_arr > 2])

[[1 2]
 [3 4]
 [5 6]]
bool_idx: 
 [[False False]
 [ True  True]
 [ True  True]]

Method 1:
 [3 4 5 6]

Method 2:
 [3 4 5 6]


<img src="images/numpy/chap5_np_16.png" style="width:50%;height:50%;">

#### 2.4 Phép toán trên mảng 

Phép cộng giữa hai mảng 

In [20]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Tổng của 2 mảng, cả 2 cách đều cho cùng một kết quả 
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


<img src="images/numpy/chap5_np_18.png" style="width:30%;height:30%;">

Phép trừ giữa hai mảng

In [21]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Phép trừ của 2 mảng, cả 2 cách đều cho cùng một kết quả 
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


<img src="images/numpy/chap5_np_19.png" style="width:30%;height:30%;">

Phép nhân giữa hai mảng 

In [22]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Phép nhân 
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


<img src="images/numpy/chap5_np_20.png" style="width:30%;height:30%;">

Phép chia giữa hai mảng

In [23]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Phép chia 
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


<img src="images/numpy/chap5_np_21.png" style="width:30%;height:30%;">

Tính căn bậc 2 cho từng phần tử

In [24]:
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Phép lấy căn 
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Nhân giữa hai vector (inner product)

In [25]:
import numpy as np

v = np.array([9,10])
w = np.array([11, 12])

# Nhân giữa 2 vector, cả 2 đều cho kết quả 219 
print(v.dot(w))
print(np.dot(v, w))

219
219


Nhân giữa vector và ma trận 

In [26]:
import numpy as np

X = np.array([[1,2],[3,4]])
v = np.array([9,10])

# Nhân giữa Matrix và vector, cả 2 đều cho kết quả array [29 67]
print(X.dot(v))
print(np.dot(X, v))

[29 67]
[29 67]


Nhân giữa matrix và matrix 

In [27]:
import numpy as np

X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])

# Nhân giữa matrix và matrix; cả 2 cách đều cho cùng kết quả 
# [[19 22]
#  [43 50]]
print(X.dot(Y))
print(np.dot(X, Y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Tính tổng cho một mảng numpy

In [28]:
import numpy as np

x = np.array([[1,2],[3,4]])

# Tổng các phần tử của mảng; prints "10"
print(np.sum(x))  

# Tính tổng theo từng cột 
print(np.sum(x, axis=0))  

# Tính tổng theo từng hàng
print(np.sum(x, axis=1)) 

10
[4 6]
[3 7]


<img src="images/numpy/chap5_np_27.png" style="width:30%;height:30%;">

Chuyển vị cho một ma trận

In [29]:
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"


[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


<img src="images/numpy/chap5_np_29.png" style="width:30%;height:30%;">

In [30]:
# Lưu ý rằng việc chuyển vị cho vector sẽ không làm gì cả.
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[1 2 3]
[1 2 3]


#### 2.5 Broadcasting

Broadcasting cho phép thực thi các phép toán trên các mảng có kích thước khác nhau.

Ví dụ: chúng ta muốn cộng vector cho mỗi hàng của ma trận. Chúng ta có thể làm như sau:

In [31]:
import numpy as np

X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
Y = np.empty_like(X)

# Cách 1: Thêm vector v vào mỗi hàng của ma trận X bằng vòng lặp 
for i in range(4):
    Y[i, :] = X[i, :] + v
    
print('Matrix X: \n', X)
print('\nVector v: \n', v)
print('\nMatrix Y: \n', Y)

Matrix X: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Vector v: 
 [1 0 1]

Matrix Y: 
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Cách này hoạt động bình thường với ma trận X nhỏ. Khi ma trận X lớn, việc sử dụng vòng lặp này sẽ rất chậm.

Chúng ta có thể thực hiện mục đích trên bằng cách xếp chồng nhiều bản sao của v theo chiều dọc, sau đó thực hiện phép tính tổng với X. Chúng ta có thể thực hiện phương pháp này như sau:

In [32]:
import numpy as np

X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])

# Xếp chồng 4 bản sao của v lên nhau:
V_t = np.tile(v, (4, 1))

# Thực hiện phép cộng
Y = X + V_t

print('Matrix X: \n', X)
print('\nVector v: \n', v)
print('\nMatrix v: \n', V_t)
print('\nMatrix Y: \n', Y)

Matrix X: 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Vector v: 
 [1 0 1]

Matrix v: 
 [[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]

Matrix Y: 
 [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<img src="images/numpy/chap5_np_31.png" style="width:50%;height:50%;">

Numpy broadcasting cho phép chúng ta thực thi tính toán này mà không cần phải làm thêm các bước thêm nào.

In [33]:
import numpy as np

X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
Y = X + v 
print(Y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<img src="images/numpy/chap5_np_32.png" style="width:50%;height:50%;">

### Tài liệu tham khảo 

[1] [CS231n Convolutional Neural Networks - Python Numpy Tutorial](http://cs231n.github.io/python-numpy-tutorial/#numpy-datatypes)