### Đại Số Tuyến Tính 

<img src="images/Linear-Algebra/intro2.png" style="width:80%;height:80%;"> 


Đại số tuyến tính là một công cụ toán học được ứng dụng nhiều trong Machine Learning / Deep Learning. Một cách hiểu đơn giản, nó là một kỹ thuật giúp chúng ta có thể thao tác nhiều dữ liệu một cách đồng thời. 

Đại số tuyến tính cung cấp một số cấu trúc như: vec-to, ma trận cùng với các phép toán nhân, chia, cộng, trừ... giữa chúng. 

Nội dung bài viết này được tham khảo trong bài viết [Linear Algebra for Deep Learning](https://towardsdatascience.com/linear-algebra-cheat-sheet-for-deep-learning-cd67aba4526c)

### Đại số tuyến tính giúp chúng ta như thế nào?

Trước hết, chúng ta hãy cùng nhau xét bài toán nhân giá trị của 2 mảng với nhau. Với cách thông thường sử dụng vòng lặp `for` để duyệt từng phần tử:

In [1]:
# Multiply two arrays 
x = [1,2,3]
y = [2,3,4]
product = []
for i in range(len(x)):
    product.append(x[i]*y[i])
    
print(product)

[2, 6, 12]


Sử dụng đại số tuyến tính, đưa các giá trị vào thành vector:

In [2]:
import numpy as np 

# Linear algebra version
x = np.array([1,2,3])
y = np.array([2,3,4])
x * y

array([ 2,  6, 12])

Việc sử dụng các phép toán trong đại số tuyến tính giúp chúng ta tính toán nhanh hơn và câu lệnh đơn giản hơn so với cách tính thông thường. Chúng ta hãy cùng nhau xét các nội dung sau:

### Nội dung 

1. Vectors
    - Ký hiệu 
    - Vectors trong hình học 
    - Scalar operations
    - Elementwise operations
    - Dot product
    - Hadamard product
    
2. Matrices
    - Kích thước ma trận 
    - Scalar operations
    - Elementwise operations
    - Hadamard product
    - Matrix transpose (ma trận chuyển vị)
    - Matrix multiplication (nhân ma trận)
    
3. Numpy
    - Dot product
    - Broadcasting

### 1. Vectors 

Vectors là mảng 1 chiều của một số hay các số hạng. Trong hình học, vectors bao gồm độ lớn và hướng của nó. Ví dụ vector [-2, 5] có hướng sang trái -2 và đi lên 5.

Vectors có nhiều chiều được gọi là Matrix.

#### 1.1 Ký hiệu 

Có nhiều cách ký hiệu vectors khác nhau, hình ảnh bên dưới miêu tả một số cách ký hiệu thường gặp:

<img src="images/Linear-Algebra/la_0.png" style="width:30%;height:30%;"> 


#### 1.2 Vectors trong hình học 

Vector thường đại diện cho sự chuyển động từ một điểm, nó lưu trữ độ lớn và hướng đi. Độ lớn của nó bằng chiều dài của cạnh huyền. Ví dụ vector [-2, 5] có hướng sang trái -2 và đi lên 5, độ lớn: $\sqrt{29}$.

<img src="images/Linear-Algebra/la_1.png" style="width:40%;height:40%;"> 



#### 1.3 Scalar operations

Scalar là một vô hướng hay một số. Scalar operations là các phép toán liên quan giữa vô hướng và vector. Chúng ta có thể thay đổi toàn bộ giá trị của vector bằng các phép toán: cộng, trừ, nhân, chia, ...

<img src="images/Linear-Algebra/la_2.png" style="width:20%;height:20%;"> 



#### 1.4 Elementwise operations

Khi thực hiện các phép toán: cộng, trừ, nhân, chia... các vector, Elementwise cho phép thực hiện các phép toán này từng vị trí tương ứng giữa các Vector. Ví dụ: phần tử thứ 1 của Vecto A sẽ thực hiện cộng với phần tử thứ 1 của Vector B, phần tử thứ 2 của A sẽ thực hiện tương ứng với phần tử thứ 2 của B. 

<img src="images/Linear-Algebra/la_3.png" style="width:30%;height:30%;"> 


In [3]:
y = np.array([1,2,3])
x = np.array([2,3,4])

print(x + y)
print(x - y)
print(x / y)

[3 5 7]
[1 1 1]
[2.         1.5        1.33333333]


#### 1.5 Phép nhân Vector 

Có 2 kiểu nhân Vector là: phép Dot product và Hadamard product.


#### 1.5.1 Dot product 

Tích của 2 vector sẽ là một vô hướng (scalar).

<img src="images/Linear-Algebra/la_4.png" style="width:30%;height:30%;"> 


In [4]:
y = np.array([1,2,3])
x = np.array([2,3,4])
np.dot(y,x)

20

#### 1.5.2 Hadamard product 

Hadamard product sẽ thực hiện phép nhân elementwise để tạo ra vector mới.

<img src="images/Linear-Algebra/la_5.png" style="width:30%;height:30%;"> 


In [5]:
y = np.array([1,2,3])
x = np.array([2,3,4])
y * x 

array([ 2,  6, 12])

### 2. Matrices

Matrices (ma trận) là một lưới hình chữ nhật (ví dụ: bảng tính Excel). 

#### 2.1 Kích thước ma trận 

Kích thước của ma trận = `[ số hàng x số cột ]`

<img src="images/Linear-Algebra/la_6.png" style="width:30%;height:30%;"> 


In [6]:
a = np.array([[1,2,3], 
             [4,5,6]])

print(a.shape)
b = np.array([[1,2,3]])

print(b.shape)

(2, 3)
(1, 3)


#### 2.2 Scalar operations

Các phép toán liên quan tới Scalar của Matrix có cách hoạt động tương tự với Vector.

<img src="images/Linear-Algebra/la_7.png" style="width:30%;height:30%;"> 


In [7]:
a = np.array([[1,2], 
              [3,4]])
a + 1

array([[2, 3],
       [4, 5]])

#### 2.3 Elementwise operations

Để có thể thực hiện phép Elemenetwise trên Matrix, các Matrix phải có **cùng kích thước** với nhau. Chúng ta sẽ thực hiện kết hợp các giá trị tương ứng với từng vị trí của các Matrix với nhau để tạo ra 1 Matrix mới. 

<img src="images/Linear-Algebra/la_8.png" style="width:30%;height:30%;"> 

In [8]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[1,2],
              [3,4]])

print("a + b: \n",a + b)

a + b: 
 [[2 4]
 [6 8]]


#### 2.4 Hadamard product

Matrix hadamard product sẽ thực hiện phép nhân elementwise.

<img src="images/Linear-Algebra/la_9.png" style="width:40%;height:40%;"> 

In [9]:
a = np.array([[2,3],
              [2,3]])

b = np.array([[3,4],
            [5,6]])
# Uses python's multiply operator
a * b

array([[ 6, 12],
       [10, 18]])

Trong Python, chúng ta có thể sử dụng phép Hadamard giữa vector và matrix. Khi đó, Python sẽ sử dụng phương thức broadcasting (chúng ta sẽ tìm hiểu phương thức này bên dưới).

<img src="images/Linear-Algebra/la_10.png" style="width:40%;height:40%;"> 

#### 2.5 Ma trận chuyển vị 

Chuyển vị của một ma trận là một ma trận mới nhận được từ ma trận cũ thông qua phép phản xạ gương qua đường chéo chính của ma trận ban đầu. Một cách hiểu đơn giản: các giá trị của hàng sẽ thành cột và cột sẽ thành hàng. 

Ma trận chuyển vị thường được ký hiệu bằng chữ $T$. Ví dụ chuyển vị của ma trận $M$ được ký hiệu $M^T$

Ví dụ: với M là ma trận ban đầu, T là ma trận chuyển vị.
<img src="images/Linear-Algebra/la_11.png" style="width:20%;height:20%;"> 

Nếu $A^T = A$ thì ta nói A là một **ma trận đối xứng**.

In [10]:
a = np.array([[1, 2], 
              [3, 4]])

print(a.T)

[[1 3]
 [2 4]]


#### 2.6 Matrix multiplication (nhân ma trận)

Cho hai ma trận $A (m$ x $n), B (n $ x $p)$, tích của hai ma trận được ký hiệu là $C = AB$ khi đó $C$ có kích thước $m$ x $p$. Ma trận C được tạo thành được tính như hình dưới đây:

<img src="images/Linear-Algebra/la_12.png" style="width:40%;height:40%;"> 

**Chú ý:** để nhân được hai ma trận, số cột của ma trận thứ nhất phải bằng số hàng của ma trận thứ hai. 

Một số tính chất của ma trận:
   - Phép nhân ma trận **không** có tính chất giao hoán.
   - Phép nhân ma trận có tính kết hợp: $ABC = (AB)C = A(BC)$
   - Phép nhân ma trận có tính giao hoán: $A(B+C) = AB + AC$
   - Chuyển vị của một tích bằng tích chuyển vị theo thứ tự ngược lại: $(AB)^T = B^TA^T$

### 3. Numpy 

#### 3.1 Dot product

Chúng ta sẽ sử dụng function `np.dot` (numpy.dot) để thực hiện phép Dot product (nhân ma trận). Các bạn cần chú ý về kích thước của các phần tử khi thực hiên phép toán.

In [11]:
a = np.array([[1, 2]])
print('a_shape: ', a.shape)

b = np.array([[3, 4],
              [5, 6]])
print('b_shape: ', b.shape)


# Multiply
mm = np.dot(a,b)
print('mm: \n', mm)
print('mm_shape: ', mm.shape)

a_shape:  (1, 2)
b_shape:  (2, 2)
mm: 
 [[13 16]]
mm_shape:  (1, 2)


#### 3.2 Broadcasting 

Broadcasting cho phép thực thi các phép toán trên các mảng có kích thước khác nhau. Chúng ta sẽ tìm hiểu chi tiết phương pháp này trong bài [Numpy - Python](https://nbviewer.jupyter.org/github/thanhhff/AIVN-Machine-Learning/blob/master/Week%202/Python-Numpy.ipynb)

In [12]:
import numpy as np

X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
Y = X + v 
print(Y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


<img src="images/Linear-Algebra/chap5_np_32.png" style="width:50%;height:50%;"> 


### Tài liệu tham khảo 

[1] [Linear Algebra for Deep Learning](https://towardsdatascience.com/linear-algebra-cheat-sheet-for-deep-learning-cd67aba4526c)

[2] [Ôn tập đai số tuyến tính - Machine Learning Cơ Bản](https://machinelearningcoban.com)